title: Hannes Vandecasteele
description: My blog, technical notes and projects
markdown: kramdown
permalink: /blog/:title/
baseurl: ""
plugins:
  - jekyll-feed
feed:
  path: /blog/feed.xml
  posts_limit: 20
  categories: []
  tags: []
  excerpt_only: true
  custom_fields:
    - name: substack_url
      value: substack_url